### ISSUE TITLE
crypto.DEFAULT_ENCODING is deprecated

### ISSUE THREAD

**Issue by renjie1996** [walkframe/covertable#2]
I use it as per the demo example,but the error happens. node: v10.15.3
`(node:27957)` [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:27957) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:27957) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.`

**Comment by righ** [comment]
@renjie1996 Thanks for reporting this issue.
I'll check and fix it later.

**Comment by righ** [comment]
Please make sure that the errors do not happen.

**Comment by righ** [comment]
If it has not been fixed, reopen it ;)
